

export const GET_USER_EXISTING_LISTS_BEGINS = 'GET_USER_EXISTING_LISTS_BEGINS'
export const GET_USER_EXISTING_LISTS_SUCCEED ='GET_USER_EXISTING_LISTS_SUCCEED'
export const GET_USER_EXISTING_LISTS_FAILED ='GET_USER_EXISTING_LISTS_FAILED'

export const ADD_LIST_BEGINS ='ADD_LIST_BEGINS'
export const ADD_LIST_SUCCEED ='ADD_LIST_SUCCEED'
export const ADD_LIST_FAILED ='ADD_LIST_FAILED'

export const DELETE_LIST_BEGINS ='DELETE_LIST_BEGINS'
export const DELETE_LIST_SUCCEED ='DELETE_LIST_SUCCEED'
export const DELETE_LIST_FAILED ='DELETE_LIST_FAILED'


export const GET_LIST_EXISTING_ITEMS_BEGINS = 'GET_LIST_EXISTING_ITEMS_BEGINS'
export const GET_LIST_EXISTING_ITEMS_SUCCEED ='GET_LIST_EXISTING_ITEMS_SUCCEED'
export const GET_LIST_EXISTING_ITEMS_FAILED ='GET_LIST_EXISTING_ITEMS_FAILED'


export const ADD_ITEM_BEGINS = 'ADD_ITEM_BEGINS'
export const ADD_ITEM_SUCCEED ='ADD_ITEM_SUCCEED'
export const ADD_ITEM_FAILED ='ADD_ITEM_FAILED'

export const TOGGLE_ITEM_BEGINS ='TOGGLE_ITEM_BEGINS'
export const TOGGLE_ITEM_SUCCEED ='TOGGLE_ITEM_SUCCEED'
export const TOGGLE_ITEM_FAILED ='TOGGLE_ITEM_FAILED'

export const DELETE_ITEM_BEGINS ='DELETE_ITEM_BEGINS'
export const DELETE_ITEM_SUCCEED ='DELETE_ITEM_SUCCEED'
export const DELETE_ITEM_FAILED ='DELETE_ITEM_FAILED'

export const SET_VISIBILITY_FILTER ='SET_VISIBILITY_FILTER'












