export const CREATE_USER_BEGINS ='CREATE_USER_BEGINS'
export const CREATE_USER_SUCCESS= 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILED ='CREATE_USER_FAILED'

export const GET_USER_BEGINS ='GET_USER_BEGINS'
export const GET_USER_SUCCESS ='GET_USER_SUCCESS'
export const GET_USER_FAILED ='GET_USER_FAILED'





